name: CI
on: workflow_dispatch

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: windows-latest
    steps:
    - run: tree .
    - uses: actions/checkout@v2
    - run: tree .
    - run: cargo install --path gameserver
    - run: cargo install --path sdkserver
    - run: tree .
    
